# Generated by Django 4.2.16 on 2024-09-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base', models.CharField(max_length=200)),
                ('team_principal', models.CharField(max_length=200)),
                ('championship_won', models.IntegerField(default=0)),
            ],
        ),
    ]
