# Generated by Django 4.2.16 on 2024-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='base',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='championship_won',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='team_principal',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
