# Generated by Django 4.2.16 on 2024-10-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_alter_teammodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField()),
                ('championship_won', models.IntegerField(blank=True, default=0)),
                ('team', models.ManyToManyField(to='teams.teammodel')),
            ],
        ),
    ]
